import type { RepoAnalysis, Feature } from './types.js';

export class MarkdownGenerator {
  /**
   * Generate a markdown report from analysis results
   */
  generate(analysis: RepoAnalysis): string {
    const sections = [
      this.generateHeader(analysis),
      this.generateSummary(analysis),
      this.generateFeatures(analysis.features),
      this.generateConflicts(analysis),
      this.generateFooter(analysis),
    ];

    return sections.join('\n\n---\n\n');
  }

  private generateHeader(analysis: RepoAnalysis): string {
    return `# 🧠 Show Me Your Think

**Repository:** \`${analysis.repoOwner}/${analysis.repoName}\`
**Analyzed at:** ${analysis.analyzedAt.toLocaleString()}`;
  }

  private generateSummary(analysis: RepoAnalysis): string {
    const { summary } = analysis;

    return `## 📊 Summary

- **Active branches:** ${summary.totalActiveBranches}
- **Main themes:** ${summary.mainThemes.length > 0 ? summary.mainThemes.join(', ') : 'None identified'}
- **Potential conflicts:** ${summary.potentialConflicts.length} detected`;
  }

  private generateFeatures(features: Feature[]): string {
    if (features.length === 0) {
      return `## 🚀 Active Features\n\n*No active features found.*`;
    }

    // Sort by confidence score (highest first)
    const sortedFeatures = [...features].sort((a, b) => b.intent.confidence - a.intent.confidence);

    const featureBlocks = sortedFeatures.map((feature, index) => {
      return this.generateFeatureBlock(feature, index + 1);
    });

    return `## 🚀 Active Features\n\n${featureBlocks.join('\n\n')}`;
  }

  private generateFeatureBlock(feature: Feature, index: number): string {
    const { branch, commits, pr, intent, relatedFeatures } = feature;

    // Confidence indicator
    const confidenceEmoji = this.getConfidenceEmoji(intent.confidence);

    // Related features summary
    const relatedSummary =
      relatedFeatures.length > 0
        ? relatedFeatures
            .map((rel) => {
              const emoji = this.getRelationshipEmoji(rel.relationship);
              return `  - ${emoji} ${rel.relationship}: ${rel.description}`;
            })
            .join('\n')
        : '  *No related features*';

    return `### ${index}. \`${branch.name}\` ${confidenceEmoji}

**Last updated:** ${branch.lastCommitDate.toLocaleDateString()} by ${branch.author}
**Commits:** ${commits.length} | **Files changed:** ${[...new Set(commits.flatMap((c) => c.filesChanged))].length}
${pr ? `**PR:** #${pr.number} - ${pr.title}` : ''}

#### 🎯 What
${intent.what}

#### 💡 Why
${intent.why}

#### 🏗️ Architectural Impact
${intent.architecturalImpact}

#### 🔗 Related Features
${relatedSummary}

<details>
<summary>📝 Commit History</summary>

${commits.map((c) => `- \`${c.sha.substring(0, 7)}\` ${c.message} (${c.date.toLocaleDateString()})`).join('\n')}

</details>`;
  }

  private generateConflicts(analysis: RepoAnalysis): string {
    const { summary } = analysis;

    if (summary.potentialConflicts.length === 0) {
      return `## ⚠️ Potential Conflicts\n\n✅ No conflicts detected between active features.`;
    }

    const conflictList = summary.potentialConflicts.map((conflict) => `- ${conflict}`).join('\n');

    return `## ⚠️ Potential Conflicts\n\n${conflictList}`;
  }

  private generateFooter(_analysis: RepoAnalysis): string {
    return `## 📌 Notes

- Analysis based on branches active within the last 30 days
- "Why" analysis powered by Claude AI
- Confidence scores indicate the reliability of AI interpretation

---

*Generated by [show-me-your-think](https://github.com/daniyuu/show-me-your-think)*`;
  }

  private getConfidenceEmoji(confidence: number): string {
    if (confidence >= 0.9) return '🟢';
    if (confidence >= 0.7) return '🟡';
    return '🔴';
  }

  private getRelationshipEmoji(
    relationship: 'depends-on' | 'conflicts-with' | 'builds-on' | 'related-to'
  ): string {
    const emojiMap = {
      'depends-on': '🔗',
      'conflicts-with': '⚠️',
      'builds-on': '🏗️',
      'related-to': '🔄',
    };
    return emojiMap[relationship];
  }
}
